//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace losk_3.BasaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledEquipment
    {
        public int InstallationID { get; set; }
        public Nullable<int> SubscriberID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Subscribers Subscribers { get; set; }
    }
}
