//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace losk_3.BasaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceStats
    {
        public int StatID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> TotalInstalled { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
